# Generated by Django 4.2.4 on 2023-09-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAPI', '0002_city_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
